baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5
disqusShortname = "logan__connolly"

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Portfolio"
    subtitle = "A collection of projects"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Portfolio"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "timeline"
        name = "Timeline"
        url = "/timeline"
