baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5
disqusShortname = "logan__connolly"

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Logan Connolly"
    subtitle = "Portfolio"
    keywords = ""
    copyright = "Logan Connolly"
    menuMore = "Show more"
    readMore = "more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Posts"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "timeline"
        name = "Timeline"
        url = "/timeline"
